import os
import subprocess
import click

def setup_django_web_project(project_name, base_dir, db_type, auth_type):
    """
    Sets up a Django web project with the specified configurations.
    Args:
        project_name (str): The name of the Django project.
        base_dir (str): The base directory where the project will be created.
        db_type (str): The type of database to use (e.g., SQLite, PostgreSQL).
        auth_type (str): The type of authentication to use (e.g., session, JWT).
    """
    project_path = os.path.join(base_dir, project_name)

    try:
        # Step 1: Install Django if not installed
        click.echo("Installing Django...")
        subprocess.run(["pip", "install", "django"], check=True)
        click.echo("Django installed successfully!")
        # Step 2: Create Django project
        click.echo(f"Creating Django project at {project_path}...")
        subprocess.run(["django-admin", "startproject", project_name], check=True)
        click.echo("Django project created successfully!")
        # Step 3: Navigate into project and create main app
        if os.path.exists(project_path):
            os.chdir(project_path)
        else:
            raise FileNotFoundError(f"The directory {project_path} does not exist.")
        click.echo("Creating main app...")
        subprocess.run(["python", "manage.py", "startapp", "main"], check=True)
        click.echo("Main app created successfully!")

        # Step 4: Update settings.py
        click.echo("Updating settings.py...")
        settings_path = os.path.join(project_path, project_name, "settings.py")
        update_settings(settings_path, db_type)
        click.echo("settings.py updated successfully!")

        # Step 5: Create folders for templates and static
        click.echo("Creating templates directory...")
        os.makedirs(os.path.join(project_path, "templates"), exist_ok=True)
        click.echo("templates directory created successfully!")
        
        click.echo("Creating static directory...")
        os.makedirs(os.path.join(project_path, "static"), exist_ok=True)
        click.echo("static directory created successfully!")
        
        # Step 6: Create requirements.txt
        click.echo("Creating requirements.txt...")
        requirements_path = os.path.join(project_path, "requirements.txt")
        with open(requirements_path, "w") as f:
            f.write("Django\n")

        click.echo("requirements.txt created successfully! to actually get all your dependencies, run `pip freeze > requirements.txt`")
        
        # Step 7: Create .gitignore
        click.echo("Creating .gitignore...")
        gitignore_path = os.path.join(project_path, ".gitignore")
        with open(gitignore_path, "w") as f:
            f.write("*.pyc\n")
            f.write("__pycache__/\n")
            f.write("db.sqlite3\n")
            f.write(".env\n")
        click.echo(".gitignore created successfully!")
        
        # Step 8: Initialize git repository
        click.echo("Initializing git repository...")
        subprocess.run(["git", "init"], check=True)
        click.echo("Git repository initialized successfully!")
        
        # Step 9: Create README.md
        click.echo("Creating README.md...")
        readme_path = os.path.join(project_path, "README.md")
        with open(readme_path, "w") as f:
            f.write(f"# {project_name}\n")
            f.write("This is a Django web project.\n")
        click.echo("README.md created successfully!")
        
        # Step 10: Create .env file
        click.echo("Creating .env file...")
        env_path = os.path.join(project_path, ".env")
        with open(env_path, "w") as f:
            f.write("DEBUG=True\n")
            f.write("SECRET_KEY='your_secret_key'\n")
            f.write("ALLOWED_HOSTS='localhost,127.0.1'\n")
        click.echo(".env file created successfully!")

        click.echo("✅ Django web project setup complete!")

    except Exception as e:
        click.echo(f"❌ Error setting up Django web project: {e}")


def update_settings(settings_path, db_type):
    """Adds common settings for web apps like templates and static dirs."""
    with open(settings_path, "r") as file:
        lines = file.readlines()

    new_lines = []
    for line in lines:
        new_lines.append(line)
        if line.startswith("INSTALLED_APPS = ["):
            new_lines.append("    'main', # Generated by pywebwizard-cli\n")
        if line.startswith("DATABASES = {"):
            new_lines.append("#Generated by pywebwizard-cli {\n")
            
            if db_type.lower() == "sqlite":
                new_lines.append(" {\n")
            elif db_type.lower() == "postgresql":
                new_lines.append("    'default': {\n")
                new_lines.append("        'ENGINE': 'django.db.backends.postgresql',\n")
                new_lines.append("        'NAME': 'your_db_name',\n")
                new_lines.append("        'USER': 'your_db_user',\n")
                new_lines.append("        'PASSWORD': 'your_db_password',\n")
                new_lines.append("        'HOST': 'localhost',\n")
                new_lines.append("        'PORT': '5432',\n")
                new_lines.append("    },\n")
            elif db_type.lower() == "mysql":
                new_lines.append("    'default': {\n")
                new_lines.append("        'ENGINE': 'django.db.backends.mysql',\n")
                new_lines.append("        'NAME': 'your_db_name',\n")
                new_lines.append("        'USER': 'your_db_user',\n")
                new_lines.append("        'PASSWORD': 'your_db_password',\n")
                new_lines.append("        'HOST': 'localhost',\n")
                new_lines.append("        'PORT': '3306',\n")
                new_lines.append("    },\n")
            else:
                raise ValueError(f"Unsupported database type: {db_type}")

    # Add static and templates settings at the bottom
    new_lines.append("\n")
    new_lines.append("# Templates and Static Config\n")
    new_lines.append("STATIC_URL = '/static/'\n")
    new_lines.append("STATICFILES_DIRS = [BASE_DIR / 'static']\n")
    new_lines.append("TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']\n")

    with open(settings_path, "w") as file:
        file.writelines(new_lines)
